services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama_volume:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:11434/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ollama-pull:
    image: docker/genai:ollama-pull
    env_file:
      - .env

volumes:
  ollama_volume: